/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RawMaterialRouteImport } from './routes/raw-material'
import { Route as IndexRouteImport } from './routes/index'

const RawMaterialRoute = RawMaterialRouteImport.update({
  id: '/raw-material',
  path: '/raw-material',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/raw-material': typeof RawMaterialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/raw-material': typeof RawMaterialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/raw-material': typeof RawMaterialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/raw-material'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/raw-material'
  id: '__root__' | '/' | '/raw-material'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RawMaterialRoute: typeof RawMaterialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/raw-material': {
      id: '/raw-material'
      path: '/raw-material'
      fullPath: '/raw-material'
      preLoaderRoute: typeof RawMaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RawMaterialRoute: RawMaterialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
